### ISSUE TITLE
グループのAPIトークンでアップロードしたい

### ISSUE THREAD

**Issue by tnj** [DeployGate/deploygate-issues#2]
- JenkinsやTravisなどにセットする用に、人と紐付かない API トークンが欲しい。
- 複数個発行できて、権限が分けられたりするとなお良いけどそれは別 issue でやろう

**Comment by kyoro** [comment]
https://deploygate.com/docs/api

こちら、グループのトークンを使ってアップロード出きるように’機能が追加されました！
CIなどでの取り扱いに便利です。ぜひご活用ください。
